// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3SW3NtXA69bjwDg8sx33y7beWYTGcM5U',
    appId: '1:385485751892:web:0b9762083eacf534b80fc1',
    messagingSenderId: '385485751892',
    projectId: 'n-app-d9792',
    authDomain: 'n-app-d9792.firebaseapp.com',
    storageBucket: 'n-app-d9792.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_PFflQM8P8l4v3DHtSfLUu4gYaagF8P4',
    appId: '1:385485751892:android:1b8321c6d8f77f00b80fc1',
    messagingSenderId: '385485751892',
    projectId: 'n-app-d9792',
    storageBucket: 'n-app-d9792.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC33aKNR36xnKxvalpZvSHRS8VqnJMJP2s',
    appId: '1:385485751892:ios:b0632b2fa0cc01d5b80fc1',
    messagingSenderId: '385485751892',
    projectId: 'n-app-d9792',
    storageBucket: 'n-app-d9792.appspot.com',
    iosBundleId: 'com.example.myportfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC33aKNR36xnKxvalpZvSHRS8VqnJMJP2s',
    appId: '1:385485751892:ios:b0632b2fa0cc01d5b80fc1',
    messagingSenderId: '385485751892',
    projectId: 'n-app-d9792',
    storageBucket: 'n-app-d9792.appspot.com',
    iosBundleId: 'com.example.myportfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3SW3NtXA69bjwDg8sx33y7beWYTGcM5U',
    appId: '1:385485751892:web:25f847d931a52bafb80fc1',
    messagingSenderId: '385485751892',
    projectId: 'n-app-d9792',
    authDomain: 'n-app-d9792.firebaseapp.com',
    storageBucket: 'n-app-d9792.appspot.com',
  );
}
